### ISSUE TITLE
Write official project plan

### ISSUE THREAD

**Issue by KodingKing99** [KodingKing99/4th_dimension#12]
Refactor our current req document.
As a developer/customer, I want to see a project plan that has
- [x] Tool Stack
- [ ] Setup Instructions
- [ ] Configuration management policies and procedures in your README.md file
- [x] A summary of the project being built
- [x] A description of team organization
- [x] A description of the overall software development process (provided by the instructor)
- [x] Policies, procedures, or tools for communication, including plans for team meetings, online-coordination, reporting, etc.
- [ ] Risk analysis
- [x] reference to the README.md for the configuration management plan
